### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mayankmohak** [mayankmohak/animate-sort#1]
Provide documentation for the project on basis of below points :
1. Aim / About.
2. Installation. (npm i)
3. Contributing Guidelines.

ThankYou,

**Comment by RaamAnalyst** [comment]
Enhanced Documentation. Kindly approve PR #4

**Comment by mayankmohak** [comment]
Sure @RaamAnalyst  
That was nice to see you working so hard on documentation.

**Comment by mayankmohak** [comment]
Sure @RaamAnalyst  
That was nice to see you working so hard on documentation.
